#language: objective-c # can this be removed?
language: c
os:
  - osx

before_install:
#  - sh theos/git-submodule-recur.sh init
  - brew update
  - brew install dpkg
  - brew install ldid

install: true

script: 
  - sed -i -- 's/-Zlzma/-Zgzip/g' theos/makefiles/package/deb.mk
  - export THEOS=theos/
  - export PATH=$THEOS/bin:$PATH
  - make package messages=yes
